### ISSUE TITLE
Text cursor moves to the beginning after immediately clear the editor content

### ISSUE THREAD

**Issue by zhu-kai** [draft-js-plugins/draft-js-plugins#2469]
## Environment

"draft-js": "^0.11.7",
"@draft-js-plugins/editor": "^4.1.0",

"@draft-js-plugins/emoji": "^4.5.5", 

## Description
I type something in the editor and hit Enter or click the button to clear the editor via `EditorState.createEmpty()`. 
If I continue to type some words, the text cursor moves to the beginning after I type the first letter.

This problem can be fixed by this method in the original Draft.js Editor. https://github.com/facebook/draft-js/issues/73#issuecomment-191394559
However, this approach doesn't work in draft-js-plugins/editor

## Reproducible Demo
https://codesandbox.io/s/draft-editor-example-ijie2

## My solution

In the `packages/editor/src/Editor/index.tsx`, I replace `moveSelectionToEnd` to `EditorState.moveFocusToEnd` in line 111 and 140.
Change from: 
```
    this.onChange(moveSelectionToEnd(editorState));
```
to: 
```
this.onChange(EditorState.moveFocusToEnd(editorState));
```
After the replacement, this issue is fixed.

**Comment by fxOne** [comment]
This is the commit which changed `EditorState.moveFocusToEnd` to `moveSelectionToEnd(editorState)`: https://github.com/draft-js-plugins/draft-js-plugins/commit/d9ba2c846c98fe8087aa3228822babbefe93c903
Unfortunately, I don't think @nikgraf will remember the sticker and focus issues after 6 years.
So it looks like the solution requires some trial and error.

**Comment by zhu-kai** [comment]
This issue comes back in v4.1.2

**Comment by execto** [comment]
@fxOne  Should this be fixed in 4.2.0?

**Comment by execto** [comment]
Confirm, same issue

**Comment by cabutler10** [comment]
Hi. I am using v4.1.3 and this issue still happening. You can see here in the original sandbox with upgraded @draft-js-plugins/editor:
https://codesandbox.io/s/draft-editor-example-forked-6p1joi?file=/src/App.js:163-187
