### ISSUE TITLE
Editor throws an "Cannot read property 'size' of undefined" error when using custom decorators

### ISSUE THREAD

**Issue by GabrielDuarteM** [draft-js-plugins/draft-js-plugins#995]
I'm having a bit of trouble making the editor of `draft-js-plugins-editor` work with custom decorators when I use EditorState.createWithContent passing them as a parameter.

When I do that, the editor crashes, throwing a `Cannot read property 'size' of undefined` error. You can reproduce the error here: [Reproducible example](https://stackblitz.com/edit/err-draft-js-plugins?file=TestEditor.js)

If you remove the `decorators` parameter on line 82 (`editorState: EditorState.createWithContent(convertFromRaw(initState)),`), the error does not happen, but the decorators are not applied to the editor.

Am I doing something wrong?

Edit: Looks like the error happens on [this line](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-plugins-editor/src/Editor/index.js#L71)

**Comment by linonetwo** [comment]
Seem to be a recent bug?

**Comment by GabrielDuarteM** [comment]
Looks like it. 

It was probably introduced in the following commit, at 14 Nov: e3d2c739c930aec545c511f4a1f1e6efcee95b69.

**Comment by teeceepee** [comment]
encountered the same issue with custom decorators. A `CompositeDecorator` instance doesn't have a `decorators` property, so it crashed.

**Comment by iShawnWang** [comment]
emmmm, I will try to downgrade draft.js version, and any update here ?

**Comment by glenn-allen** [comment]
For anyone looking for a workaround, wrap your `CompositeDecorator` with the Draft JS Plugins' `MultiDecorator`:

```
import { CompositeDecorator } from 'draft-js';
import MultiDecorator from 'draft-js-plugins-editor/lib/Editor/MultiDecorator';

....
const createDecorator = (...) => {
    const decorators = ...;
    return new MultiDecorator([new CompositeDecorator(decorators)]);
};
```

**Comment by rakeen** [comment]
@glenn-allen Hey I tried the `MultiDecorator` wrapper and looks like the original decorator isn't working for some reason.

https://codesandbox.io/s/kk7nko5ow3

**Comment by GabrielDuarteM** [comment]
@rakeen you are probably just forgetting to add the decorators property that draftjs plugins require. 

https://github.com/draft-js-plugins/draft-js-plugins/blob/master/FAQ.md#how-can-i-use-custom-decorators-with-the-plugin-editor

**Comment by rakeen** [comment]
@GabrielDuarteM  Yes it was indeed the case. thanks.

**Comment by juliankrispel** [comment]
this should be fixed now with the latest version of draft-js-plugin-editor

**Comment by winghouchan** [comment]
I'm not sure this issue is fixed. I'm still experiencing it in 2.0.7.

**Comment by pcsms** [comment]
Isn't fixed. I can't use custom decorators with draft-js-mention-plugin

**Comment by freedomlang** [comment]
@winghouchan @pcsms @juliankrispel  [reproduced](https://stackblitz.com/edit/err-draft-js-plugins-txfxcl?file=TestEditor.js) with latest version of draft-js-plugin-editor, will recheck it in the next few days

**Comment by juliankrispel** [comment]
@freedomlang properly fixed now https://codesandbox.io/s/q8qz5286z4
